Added Slideshow feature
dear-digital/shopify-theme-skeleton pull request #105
Opened 2023-12-01 08:03 UTC by tanujbordikar

Solved the Issue no. #72 

**JS Implementation:** Incorporate necessary JavaScript to make the slideshow interactive and dynamic.
**CSS Styling:** Apply responsive styling using the BEM (Block, Element, Modifier) methodology to ensure the slideshow adapts to various screen sizes.

https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/b60e93bf-1cd4-4422-bb3f-ca86c4f38e36

2023-12-01 09:47 UTC, mihir-bombay-studio requested changes
Can you redo the following changes? Thanks!

2023-12-01 09:47 UTC, mihir-bombay-studio commented on sections/slideshow.liquid
> +<script src="{{ 'slideshow.js' | asset_url }}" defer="defer"></script>
slideshow should work without saving, checkout the [theme editor events](https://shopify.dev/docs/themes/architecture/sections/integrate-sections-with-the-theme-editor) for re-running the scripts when the section in editor changes

2023-12-01 09:47 UTC, mihir-bombay-studio commented on sections/slideshow.liquid
> +      </svg>
svg's can come from snippets, you can also pass classes as parameters inside render liquid tag

2023-12-01 09:47 UTC, mihir-bombay-studio commented on sections/slideshow.liquid
> +          style="color:{{ text_color }};border-color:{{ text_color }};"
avoid all inline styles, instead use section.id in liquid to identify the selector and use it in style tag refer sections in dawn theme. If using tailwind create seperate schemas for dynamically adding tailwind classes refer the demo section.

2023-12-01 09:47 UTC, mihir-bombay-studio commented on sections/slideshow.liquid
> +<div id="sliderContainer" class="slider-container" style="color:{{ text_color }};">
Use appropriate BEM style classes everywhere in the section

2023-12-02 07:02 UTC, mihir-bombay-studio requested changes
@tanujbordikar prepend all file names /assets and /sections with dev__.
Review the entire code once, compare it with Dawn slideshow section, use chatgpt to optimise and correct the code.

2023-12-02 07:02 UTC, mihir-bombay-studio commented on sections/slideshow.liquid
> +{% endif %}
slideshow will only work in theme editor, not on live website with this condition.

2023-12-02 07:02 UTC, mihir-bombay-studio commented on sections/slideshow.liquid
> +</script>
blank script

2023-12-02 13:01 UTC, tanujbordikar commented
Sir can you provide more information about the re-running the scripts when the section in editor changes. I have tried to solve it but couldn't able to achieve what you have asked for!

2024-02-05 06:18 UTC, closed without merging