Added Tailwind to Logo Carousel
dear-digital/shopify-theme-skeleton pull request #133
Opened 2023-12-02 18:09 UTC by anishdalvi

Solved: #99 

- Responsive in nature
- Logo Widths can be controlled from Theme Editor

[View Demo Video](https://drive.google.com/file/d/1CZ2csvaaj0jHvWFf1dU2778ROkFYhvb6/view?usp=drive_link)

2023-12-03 08:39 UTC, mihir-bombay-studio requested changes
@anishdalvi can you check out the changes? Thanks!

2023-12-03 08:39 UTC, mihir-bombay-studio commented on sections/dev__logo-carousel.liquid
> +}
Generic styles are not required

2023-12-03 08:39 UTC, mihir-bombay-studio commented on sections/dev__logo-carousel.liquid
> +  }
These styles are not required as they can be added from tailwind classes

2023-12-03 08:39 UTC, mihir-bombay-studio commented on sections/dev__logo-carousel.liquid
> +<div class="logos overflow-hidden whitespace-nowrap relative {{ section.settings.style--logos }}" >
no hardcoded classes required. they can be added as default or presets in .style--logos shema

2023-12-03 08:39 UTC, mihir-bombay-studio commented on sections/dev__logo-carousel.liquid
> +  {% capture widths %}{{ section.settings.logo_width }}, {{ section.settings.logo_width | times: 1.5 | round }}, {{ section.settings.logo_width | times: 2 }}{% endcapture %}
All styles can come from theme editor with schemas

2023-12-03 08:39 UTC, mihir-bombay-studio commented on sections/dev__logo-carousel.liquid
> +            }}
you can also add classes to image using [this](https://github.com/dear-digital/shopify-theme-skeleton/pull/109#discussion_r1412744457) technique

2023-12-04 16:05 UTC, anishdalvi commented on layout/theme.liquid
> +          }
Okay Cool!

2023-12-04 16:12 UTC, anishdalvi commented
Changes Done!

2023-12-05 05:20 UTC, mihir-bombay-studio commented on config/settings_schema.json
> +                "default": "@layer utilities {.pause { animation-play-state: paused;}}"
settings_schema.json file should not have any changes, this value of tailwind class should be added to settings_data.json instead it could be done via the theme editor as well in design mode. shopify cli needs to have 
--theme-editor-sync [flag](https://shopify.dev/docs/themes/tools/cli/commands) enabled

2023-12-05 12:53 UTC, anishdalvi commented on config/settings_schema.json
> +                "default": "@layer utilities {.pause { animation-play-state: paused;}}"
Thank You for this Information Sir. I have made the changes, please Check!

2023-12-06 11:03 UTC, mihir-bombay-studio approved these changes

2023-12-06 11:03 UTC, merged