Offers Card with necessary CSS
dear-digital/shopify-theme-skeleton pull request #14
Opened 2023-11-17 12:42 UTC by tanujbordikar

Here in this Issue i have made a simple offer cards and tried to refer [yummygums](https://www.yummygums.com/).

Solves Issue no #7 - Schema Integration for [Section Name] = "cards" which offers:
- Responsive offer cards.
- Hovering effect.

Video: 

https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/0041a30e-1096-4623-ab7c-0f846c0a5eef

2023-11-17 12:51 UTC, mihir-bombay-studio requested changes
Can you add the schema to the section

2023-11-17 12:51 UTC, mihir-bombay-studio commented on assets/25_percent.jpg
Try avoiding images in assets unless it necessary you can use [shopify placeholders](https://www.shopify.com/partners/blog/placeholder-images) for this purpose or select from their image library in theme editor

2023-11-17 12:51 UTC, mihir-bombay-studio commented on sections/cards.liquid
only requirement for this ticket is adding the [schema](https://shopify.dev/docs/themes/architecture/sections/section-schema) based on the structure for this section

2023-11-17 13:43 UTC, tanujbordikar commented on sections/cards.liquid
Okayy got it

2023-11-17 17:47 UTC, tanujbordikar commented
Sir, can you check it now!
here the updated screenshot!
![cards](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/4d4402a1-7e7b-4cc4-ab8a-ad014980583c)

2023-11-18 06:24 UTC, mihir-bombay-studio requested changes
@tanujbordikar can you check the changes again. Thanks!

2023-11-18 06:24 UTC, mihir-bombay-studio commented on sections/cards.liquid
> +  ],
Instead of adding duplicate schemas, you can yse blocks and add a forloop to iterate over the blocks, which makes the process more clean

2023-11-18 06:24 UTC, mihir-bombay-studio commented on config/settings_data.json
try not to push any changes made to the settings_data file, you can do all changes locally and push only the relevant sections

2023-11-18 06:24 UTC, mihir-bombay-studio commented on templates/index.json
Also no need to push changes made to any templates, unless specified in the issue ticket. Because we can just use the theme editor to add the section dynamically later to the index template easily

2023-11-18 06:34 UTC, tanujbordikar commented on templates/index.json
okay i will consider all your points and make the section dynamic!

2023-11-18 06:59 UTC, closed without merging