Added Tailwind CSS to Collage Section
dear-digital/shopify-theme-skeleton pull request #140
Opened 2023-12-03 10:04 UTC by tanujbordikar

Solves Issue #118 

- Added Tailwind CSS with dynamic theme configuration

2023-12-05 05:30 UTC, mihir-bombay-studio requested changes
@tanujbordikar I've added some comments can you check them and correct wherever required in this file and also on your other PR's

2023-12-05 05:30 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
>  <div class="color-{{ section.settings.color_scheme }} gradient isolate">
no hardcoded style classes

2023-12-05 05:30 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +      <div class="inline-richtext">
missing styling class

2023-12-05 05:30 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +  <div class="page-width {{ section.settings.page-width }}">
All style classes id's should have a styles or classes keyword appended or prepended section.settings.page-width will become
section.settings.page-width-styles or section.settings.page-width-classes

2023-12-05 05:30 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +    <div class="collage {{ section.settings.collage }} {% if section.settings.mobile_layout == 'collage' %} collage--mobile{% endif %}">
mobile layout settings can also be done with tailwind classes so no need for extra mobile filters

2023-12-05 05:30 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +          <div class="collage__item {{ section.settings.collage__item }} collage__item--{{ block.type }} collage__item--{{ section.settings.desktop_layout }}">
all block level styling should be at block level only. also no need to have desktop layout as all styling is possible from tailwind classes

2023-12-05 05:30 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +                  <div class="media media--transparent ratio">
missing tailwind classes

2023-12-05 07:31 UTC, tanujbordikar commented
Hey @mihir-bombay-studio Sir, I have made the necessary changes as you said! Can you please review the new code.

2023-12-06 11:34 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +  <div class="color-{{ section.settings.color_scheme }} gradient isolate">
This element still has hardcoded classes @tanujbordikar

2023-12-06 11:36 UTC, mihir-bombay-studio commented on sections/dev__collage.liquid
> +                    <p class="collection__description text-base">{{ block.settings.collection.description }}</p>
These elements don't have tailwind schema

2023-12-09 08:11 UTC, mihir-bombay-studio approved these changes

2023-12-09 08:11 UTC, merged