Separate JS and CSS from section
dear-digital/shopify-theme-skeleton pull request #346
Opened 2024-07-26 11:19 UTC by shradhdhadeardigital

1) Separate JS and CSS from the section  
2) Update Js and Form for Product Page and Featured Product section 
3) Format Js files and update tailwind file

2024-07-26 12:34 UTC, mihir-bombay-studio requested changes
Can you check the comments and make necessary changes?

2024-07-26 12:34 UTC, mihir-bombay-studio commented on assets/dev__back-to-the-top.js
This code can be opimised. Check the same issue on other files as well. Pass it once through chatgpt or claude and ask for optimising the code. these are some questions you can ask

can you reduce the size of this code either by making it modular or removing any redundancy. ensure the functionality remains the same

Incorporate modern JavaScript features to make code cleaner and more efficient. Organize the code into smaller, more manageable functions or modules. This can help isolate functionality, making the code easier to understand and test.

Implement comprehensive error handling, especially for asynchronous operations. Optimize DOM Manipulations. Finally, establish and enforce coding standards.

2024-07-26 12:34 UTC, mihir-bombay-studio commented on sections/dev__countdown-timer.liquid
If this kind of section is added multiple times on a page then ID selector won't work. Check the same issue on other files as well

2024-07-29 04:34 UTC, shradhdhadeardigital commented on assets/dev__back-to-the-top.js
@mihir-bombay-studio 
I have tried my best to optimize JS and fixed the problem with the ID selector for multiple sections.

2024-07-30 03:52 UTC, merged