Added the newsletter section
dear-digital/shopify-theme-skeleton pull request #57
Opened 2023-11-23 10:31 UTC by tanujbordikar

Solves Issue no #46 
Added the Newsletter Section using Responsive CSS.

Screenshots:
![newsletter_schema](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/02859137-1e2b-4be1-b5d2-4504f668054d)
![newsletter](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/8da5b443-1340-4956-92a8-a39e93e213da)

2023-11-23 10:53 UTC, mihir-bombay-studio commented on sections/newsletter.liquid
> +            {{ content_for_header }}
why is there content_for_header in newsletter?

2023-11-23 10:54 UTC, mihir-bombay-studio commented on sections/newsletter.liquid
> +{% if section.settings.newsletter_enable %}
no need for this if condition, because if someone already decides to add newsletter section they would definately want to display it.

2023-11-23 10:56 UTC, tanujbordikar commented on sections/newsletter.liquid
> +            {{ content_for_header }}
I have used that for checking purpose and forget to remove, I'll commit by removing that!

2023-11-24 05:07 UTC, mihir-bombay-studio commented on sections/newsletter.liquid
> +        <form action="{{ 'https://example.com' | within: 'settings' }}" method="post" target="_blank" novalidate class="newsletter-form__form">
Instead of using this form we can use [form](https://github.com/Shopify/dawn/blob/2c847245ea3dfec6f248dcbb2dd76c4ceb65c437/sections/newsletter.liquid#L48) provided by shopify which has inbuilt customer creation and newsletter enabling capabilities ([doc](https://shopify.dev/docs/api/liquid/tags/form))

2023-11-24 10:50 UTC, mihir-bombay-studio requested changes
Let's make the section completely translatable

2023-11-24 10:50 UTC, mihir-bombay-studio commented on sections/newsletter.liquid
> +              placeholder="Email"
Placeholder text should come from the schema(Will be good for translating the website into multiple languages)

2023-11-24 10:50 UTC, mihir-bombay-studio commented on sections/newsletter.liquid
> +              Subscribe
Instead of hardcoding the text it should come from the schema(Will be good for translating the website into multiple languages)

2023-11-24 12:10 UTC, tanujbordikar commented
Hey Sir, I have made the changes by adding the schemas for email placeholder and subscribe button. 
Can you please review the updated code.

2023-11-24 16:14 UTC, merged