Schema Integration for [Section Name] = "featured-blogs"
dear-digital/shopify-theme-skeleton pull request #70
Opened 2023-11-24 21:25 UTC by kmalap05

Issue No: #62 
Schema Integration for [Section Name] = "featured-blogs"

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/9a6c590f-e966-4a4f-9bb0-ce77c3e72a83)
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/2d31e72f-053e-4611-8600-66fc356de519)
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/0818d2cc-0a8b-4ae4-8785-0d32c871151d)

2023-11-25 05:57 UTC, mihir-bombay-studio commented
can you add some liquid html that can display the blog posts inside the section. Basic structure will do

2023-11-25 10:58 UTC, kmalap05 commented
Changes made.

2023-11-26 14:22 UTC, mihir-bombay-studio requested changes
@kmalap05 Sorry for the late review. Can you check the comments and fix them? Thanks!

2023-11-26 14:22 UTC, mihir-bombay-studio commented on sections/featured-blogs.liquid
> +  style="padding-top: {{ section.settings.padding_top }}px; padding-bottom: {{ section.settings.padding_bottom }}px;"
we don't need to add a section element as shopify itself creates a section wrapper for our sections by default, we can aslo add custom classes to that wrapper from the schema(refer documentation). Adding inline styles is not recommended unless necessary.

2023-11-26 14:22 UTC, mihir-bombay-studio commented on sections/featured-blogs.liquid
> +          >
use image_tag filter instead

2023-11-26 14:22 UTC, mihir-bombay-studio commented on sections/featured-blogs.liquid
> +      >View All</a
Url's and text must not be hardcoded, try taking these values from the schema.

2023-11-27 06:20 UTC, kmalap05 commented
Please verify, I have made all the changes requested.

2023-11-27 06:42 UTC, mihir-bombay-studio approved these changes

2023-11-27 06:42 UTC, merged